### ISSUE TITLE
Been a while since I've played Minecraft, remember me?

### ISSUE THREAD

**Issue by KingEdward9830** [Um-Mitternacht/Wiccan_Arts#23]
I helped get this project started, I then vanished for awhile. The reason for this is quite simple, I was bored with MC in general and needed a change of pace. LOL I see this mod is coming along nicely. Keep up the good work guys!

**Comment by darthvader45** [comment]
Same here.  Hopefully if Emoniph sees this they may get inspired, never know.  Either way, keep up the amazing work!

**Comment by Sunconure11** [comment]
Closing due to age.
