### ISSUE TITLE
So, Astral/dream walking stuff?

### ISSUE THREAD

**Issue by KingEdward9830** [Um-Mitternacht/Wiccan_Arts#30]
Guessing this isn't even on the todo list for now, but it'd be nice if the mod had it at some point. The only mods I know of that ever did something like it are Witchery and Intangible, but I want to have those sorts of abilities in modern MC versions.

**Comment by xenxero1** [comment]
Astral Projection could fit in perfectly with the way the mod seems to be going. Only issue would be figuring out balance and what stage you'd gain access to it. As well as limitation. Witchery's was underpowered and needed alot, Intagibles was abit too strong for how early you got it imo.

**Comment by Sunconure11** [comment]
It's written down, but it's not going to be touched any time soon in the actual code.

**Comment by KingEdward9830** [comment]
Witchery's version was indeed underpowered. Intangible's version would've been far less overpowered if the bodies had been handled a bit more like Witchery, IE being vulnerable and having effects on the player if destroyed while in spirit form. (For example, if destroying someone's last body would cause their spirit form to "die", their items be dropped at the location of the last body, and for them to respawn normally outside of hardcore mode. This way guarding your bodies against griefers would be mandatory, as they can destroy them and without them you die.)

**Comment by Sunconure11** [comment]
I'll add a bit onto this convo before I go off for the night. Mechanics have been written down, in various docs we have, regarding this. The general idea is that you'd have to perform specific rituals in a dimension very similar to Witchery's dream world before you can begin to figure out how to astral project. As of writing this, you'd need to create specific constructs from materials found in said world, in the dream world (this is subject to change, as there are multiple individuals involved in on this, aside from me and the two other coders, and there have been several document reforms), to start your way into figuring out how to astral project. As for AP mechanics themselves, they are a mix of witchery, intangible, some metaphysical stuff, and random ideas, which would be quite a lot to write down in this one post. Like in Witchery though, you are vulnerable at first, while astral projecting, for a player could come and snuff your life out by killing you in your sleep/meditation.

However, this is pretty far off into the future, in terms of implementation. Like, I'd say maybe very late into a future 1.12 version if I was forced to guess on an ETA TBH.

**Comment by KingEdward9830** [comment]
NP, maybe if I ever get around to learning code I could make a stand alone mod for this sort of thing, but so far I've been too lazy. lol
