### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by kalTorack** [Um-Mitternacht/Wiccan_Arts#48]
Hey! Very sorry to open a new issue, but I was wondering how I would go about using this mod?

I was also wondering if I could grab the discord!

**Comment by Ingoleth** [comment]
Well, at the moment the mod is still in an early development stage. We are currently working on moving everything to 1.12 and on getting all the "infrastructure" of the mod in place for the first release (which will be posted on Curse). Whilst I can't provide a link to download the mod as of yet, I can provide the discord link: https://discord.gg/BaqYT73
