### ISSUE TITLE
Made a backport of newest version to 1.11.2

### ISSUE THREAD

**Issue by ghost** [Um-Mitternacht/Wiccan_Arts#49]
Hello Sunconure11,

I've created a compileable backport to 1.11.2 of the newest changes. Despite the newest stuff with the fake ice blocks everything else is there. Do you need the branch to be commited?

Regards,
Avatair

**Comment by Sunconure11** [comment]
My plan is to stay on 1.12.* for now. Sorry. Plus maintaining multiple branches with the same stuff can be a pain from what I've heard.

**Comment by ghost** [comment]
Never mind :)

**Comment by Sunconure11** [comment]
I can however, offer you a position as another coder, as the other main coder is a bit too busy with life. What do you think of that? Just join this discord channel, and I'll set you up: https://discord.gg/Kk3YPW7
