### ISSUE TITLE
Potential lack of QA correspndant [Fix in desc]

### ISSUE THREAD

**Issue by xenxero1** [Um-Mitternacht/Wiccan_Arts#5]
Hello! I'm a professional QA'er with a bit of spare time on my hands, I'm quite active on a few other mod's github pages for reference. I wasn't sure how to get into contact with your team so I figured this was the best method.  I wanted to apply as a tester for the mod, and see if I can help in any way you guys need me.

Thanks,

Matt

**Comment by Sunconure11** [comment]
The mod is currently not in a state for any kind of testing. Though to be fair, there were a few builds I released just for making sure Travis was working, but they aren't functional in terms of playability. It will be a few weeks at the minimum.

**Comment by xenxero1** [comment]
Forgot to mention, I'm fairly knowledgeable when it comes to the different sects of wiccan practitioners, lore, practices, rituals, tools, ect.

And even if there is no current working version, would it be possible for me to stay in the loop with the development/ devgroup? As a long time fan of the Witchery mod, 1.10.2 feels very lacking without a similar option.

**Comment by Sunconure11** [comment]
https://discord.gg/mYezx

**Comment by Sunconure11** [comment]
I am only posting here due to stuff, as the discord will see this.

Due to the possibility of major storms, I will be off for most of the day, as my previous mobo got fried as a result of power surges.

Also, I like the structure idea, but it should be after first release. Maybe a ringfort?

**Comment by xenxero1** [comment]
Just gonna close this issue for the time being. Don't see any reason to keep it open.
