### ISSUE TITLE
Wiki Missing Cauldron Recipe(s)

### ISSUE THREAD

**Issue by CJL48** [Um-Mitternacht/Wiccan_Arts#55]
Just to let you know, the wiki is missing the recipe for the corruption effect (bone). I think that every other brew recipe is covered though.
That said, there is no existing coverage for the non-brew cauldron recipes. This includes the dye/pattern removal from the vanilla cauldron (not a problem - these are covered in minecraft's own documentation), as well as recipes that I only realized existed because I looked at the mod's code, ie. Cooking with oil or water, Fluid Creation, and Item Rituals.
I think that the cauldron cooking (using oil), and processing (honeycombs to wax and honey, hooves to slime balls, acacia wood and wormwood to dyes, using water) recipes should be included in the wiki, as they do not appear in jei- the only way to find these recipes is via experimentation or reading a specific class file. I have gotten most of these to work, so I know that they're really recipes.
I also have a question: how do the Fluid Creation and Item Ritual cauldron recipes work? Reading the code to register these doesn't make the recipes as clear as with the other types of recipes (brewing, cooking, and processing). This is particularly troubling in the case of fluid creation, as it appears to be the intended method of making honey and cooking oil. I also don't know what other blocks/items I need for the item rituals, though the code does indicate a need for energy.

I do understand that this mod is still being created: I half expect that some of these recipes are not functional yet.

Update: Nevermind. Just after posting this issue, I discovered that rituals are done with the cauldron by 1) putting in the ingredients, 2) clicking the cauldron. So item rituals work just fine. Going to see if I can get fluid creation to work.

From this page:
https://github.com/Um-Mitternacht/Witchworks/wiki/Brews

And the CauldronCrafting class:
https://github.com/Um-Mitternacht/Witchworks/blob/1.12.2/src/main/java/com/witchworks/common/crafting/cauldron/CauldronCrafting.java

Version: Public Alpha 6

**Comment by Sunconure11** [comment]
I'm going to document all of that, I just haven't gotten around to it yet.

A JEI plugin is in semi-progress, but it's still not complete.

**Comment by CJL48** [comment]
Ah. Okay. Thanks for responding - I'll admit that I made this issue as much to inform players looking for the recipes as I did to let you know.

**Comment by Sunconure11** [comment]
https://github.com/Um-Mitternacht/Witchworks/wiki/Cauldron-Recipes

I've started, but I'll finish tomorrow.

**Comment by Sunconure11** [comment]
Closing due to the repo moving.
