### ISSUE TITLE
i doesn't find what this mod does...

### ISSUE THREAD

**Issue by matyklug18** [Um-Mitternacht/Wiccan_Arts#56]
what it does? screenshots? tutorials? wiki? curse page? i will love to see what it is. it is port of witchery? i missing something?

**Comment by Sunconure11** [comment]
There's a wiki, but we are moving repos, due to this mod merging with covens.

https://github.com/Um-Mitternacht/Witchworks/wiki

https://github.com/Um-Mitternacht/Bewitchment
